# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Build Staging IPA"
  lane :staging do
    build_app(
      scheme: "reactNativeCiCd"
    )
  end

  desc "Build Production IPA"
  lane :production do
    build_app(
      scheme: "reactNativeCi"
    )

    app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_filepath: "./AuthKey.p8"
    )
    upload_to_test_flight
  end
end
